/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Sicilian Brand Colors - Dolce Sicilia
        mediterranean: {
          DEFAULT: '#004F9F',
          900: '#003A75',
          800: '#004080',
          700: '#004F9F',
          600: '#005FBF',
          500: '#3F9CDE',
          400: '#6CB5E8',
          300: '#99CEF2',
          200: '#C6E6FB',
          100: '#E6F4FC',
        },
        cream: {
          DEFAULT: '#FDFCF0',
          900: '#E8DFC8',
          800: '#EDE6D4',
          700: '#F2EDD9',
          600: '#F7F3E5',
          500: '#FDFCF0',
          400: '#FEFDF7',
          300: '#FFFEFA',
        },
        beige: {
          DEFAULT: '#E6D8B8',
          900: '#C9B586',
          800: '#D4C297',
          700: '#E6D8B8',
          600: '#EBE0C8',
          500: '#F0E8D8',
        },
        ink: {
          DEFAULT: '#2B2B2B',
          900: '#1A1A1A',
          800: '#2B2B2B',
          700: '#3D3D3D',
          600: '#4F4F4F',
          500: '#616161',
        },
        // Legacy aliases for compatibility
        gold: {
          900: '#003A75',
          800: '#004080',
          700: '#004F9F',
          600: '#005FBF',
          500: '#3F9CDE',
          400: '#6CB5E8',
          300: '#99CEF2',
          200: '#C6E6FB',
          100: '#E6F4FC',
        },
        wine: {
          900: '#FDFCF0',
          800: '#EDE6D4',
          700: '#F2EDD9',
          600: '#F7F3E5',
          500: '#004F9F',
          400: '#3D3D3D',
          300: '#4F4F4F',
          200: '#616161',
          100: '#2B2B2B',
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      fontFamily: {
        serif: ['Playfair Display', 'Georgia', 'serif'],
        sans: ['Inter', 'Helvetica Neue', 'Arial', 'sans-serif'],
        script: ['Playfair Display', 'Georgia', 'serif'],
      },
      fontSize: {
        'display': ['5.5rem', { lineHeight: '1.1' }],
        'h1': ['4.5rem', { lineHeight: '1.15' }],
        'h2': ['3.6rem', { lineHeight: '1.2' }],
        'h3': ['2.5rem', { lineHeight: '1.25' }],
        'h4': ['2rem', { lineHeight: '1.3' }],
        'h5': ['1.5rem', { lineHeight: '1.4' }],
        'h6': ['1.25rem', { lineHeight: '1.5' }],
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(24px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "slide-in-left": {
          "0%": { opacity: "0", transform: "translateX(-40px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "slide-in-right": {
          "0%": { opacity: "0", transform: "translateX(40px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.92)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "marquee": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "fade-up": "fade-up 0.6s ease-out forwards",
        "fade-in": "fade-in 0.4s ease-out forwards",
        "slide-in-left": "slide-in-left 0.7s ease-out forwards",
        "slide-in-right": "slide-in-right 0.7s ease-out forwards",
        "scale-in": "scale-in 0.6s ease-out forwards",
        "marquee": "marquee 40s linear infinite",
      },
      spacing: {
        '18': '4.5rem',
        '22': '5.5rem',
        '30': '7.5rem',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
